          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Modify deployment script based on the app type
                echo "Starting deployment script run"
                sudo java -jar '$(Pipeline.Workspace)/drop/**/target/*.jar'
        routeTraffic:
          steps:
          - script: echo routing traffic
        postRouteTraffic:
          steps:
          - script: echo health check post-route traffic
        on:
          failure:
            steps:
            - script: echo Restore from backup! This is on failure
          success:
            steps:
            - script: echo Notify! This is on success
- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'Azure for Students (6e9408e7-a3a5-44d0-80f3-65b13b7b59a9)'
    Action: 'Deploy'
    AzureSpringCloud: 'Azurespring'
    AppName: 'Application'
    UseStagingDeployment: true